{{- if .Values.ingress.api.enabled }}
{{- $values := . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.tenant.name }}
  namespace: {{ .Values.tenant.namespace }}
  {{- with .Values.ingress.api.labels }}
  labels: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.api.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.api.ingressClassName }}
  ingressClassName: {{ .Values.ingress.api.ingressClassName }}
  {{- end }}
  {{- if .Values.ingress.api.tls }}
  tls:
    {{- range .Values.ingress.api.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{include "render-url" ( dict "value" .Values.ingress.api.host "context" $values ) }}
      http:
        paths:
          - path: {{ .Values.ingress.api.path }}
            pathType: {{ .Values.ingress.api.pathType }}
            backend:
              service:
                name: minio
                port:
                  {{- if or .Values.tenant.certificate.requestAutoCert (not (empty .Values.tenant.certificate.externalCertSecret)) }}
                  name: https-minio
                  {{- else }}
                  name: http-minio
                  {{- end }}
{{ end }}
