{{- if .Values.ingress.console.enabled }}
{{- $values := . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "minio-operator.fullname" .}}-console
  namespace: {{ .Values.tenant.namespace }}
  {{- with .Values.ingress.console.labels }}
  labels: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.console.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.console.ingressClassName }}
  ingressClassName: {{ .Values.ingress.console.ingressClassName }}
  {{- end }}
  {{- if .Values.ingress.console.tls }}
  tls:
    {{- range .Values.ingress.console.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .minioBrowserRedirectURL | default (include "domains.minio" .) }}
      http:
        paths:
          - path: {{ .Values.ingress.console.path }}
            pathType: {{ .Values.ingress.console.pathType }}
            backend:
              service:
                name: {{ include "minio-operator.fullname" . }}-console
                port:
                  {{- if or .Values.tenant.certificate.requestAutoCert (not (empty .Values.tenant.certificate.externalCertSecret)) }}
                  name: https-console
                  {{- else }}
                  name: http-console
                  {{- end }}
{{ end }}
