{{ $secretName := .Values.secrets.name }}
{{ $secret := lookup "v1" "Secret" .Values.tenant.namespace $secretName }}
{{ $secret := "false" }}

{{- if not $secret }}
{{- if dig "secrets" true (.Values | merge (dict)) }}
{{- $ROOT_PASSWORD := (randAlphaNum 16 | quote)}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ dig "secrets" "name" "" (.Values | merge (dict)) }}
  namespace: {{ .Values.tenant.namespace }}
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER={{ .Values.secrets.accessKey | quote }}
    export MINIO_ROOT_PASSWORD={{$ROOT_PASSWORD}}
data:
  ## Access Key for MinIO Tenant
  accesskey: {{ dig "secrets" "accessKey" "" (.Values | merge (dict)) | b64enc }}
  ## Secret Key for MinIO Tenant
  secretkey: {{$ROOT_PASSWORD | b64enc }}
  {{- end }}
{{- end }}
