apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "jupyterhub.singleuser.fullname" . }}
data:
  {{- (.Files.Glob "configs/*.tar").AsConfig | nindent 2 }}
  startup_script.bash: |-
    {{- .Files.Get "configs/startup_script.bash" | nindent 6 }}
  jupyter_server_config.py: |-
    {{- .Files.Get "configs/jupyter_server_config.py" | nindent 6 }}
  jupyter_notebook_config.py: |-
    {{- .Files.Get "configs/jupyter_notebook_config.py" | nindent 6 }}
  .condarc.toplevel: |
    anaconda_upload: false
    channels:
      - nodefaults
    channel_priority: strict
    ssl_verify: false
  .condarc.user: |
    anaconda_upload: false
    channels:
      - http://{{ .Release.Name }}-nginx.{{ .Values.namespace }}.svc.cluster.local:8080/condapkg/
      - nodefaults
    channel_priority: strict
    ssl_verify: false
  conda_channel.yaml: |
    name: singleuser
    channels:
      - http://{{ .Release.Name }}-nginx.{{ .Values.namespace }}.svc.cluster.local:8080/condapkg/
    dependencies:
      - bokeh==3.3.4
      - cartopy==0.23.0
      - cdsdashboards-singleuser==0.6.3
      - click==8.1.3
      - confuse==2.0.1
      - coverage==7.6.1
      - cudatoolkit==11.8.0
      - dask==2024.8.2
      - dask-jobqueue==0.9.0
      - datashader==0.16.3
      - geoviews==1.11.1
      - git==2.45.2
      - holoviews==1.19.1
      - htop==3.3.0
      - imbalanced-learn==0.12.3
      - ipykernel==6.29.5
      - ipympl==0.9.4
      - ipython==8.27.0
      - ipywidgets==8.1.2
      - jhsingle-native-proxy==0.8.0
      - jupyter_bokeh==4.0.0
      - jupyter-server-proxy==4.1.0
      - jupyterhub==5.1.0
      - jupyterlab==4.1.3
      - jupyterlab_widgets==3.0.10
      - matplotlib==3.9.2
      - metaflow==2.12.15
      - msgpack-python==1.0.8
      - nb_conda_kernels==2.5.1
      - nodejs==22.6.0
      - notebook==7.1.3
      - numpy==1.26.4
      - opencv==4.9.0
      - ocl-icd-system==1.0.0
      - pandas==2.2.2
      - panel
      - param==2.1.1
      - pip==24.0
      - plotly==5.19.0
      - pyarrow==15.0.0
      - pytest==8.0.2
      - pytest-cov==4.1.0
      - python=3.11.7
      - pytorch-gpu==2.1.2
      - pyyaml==6.0.1
      - s3fs==2024.2.0
      - s3fs-fuse==1.94
      - scikit-learn====1.4.1.post1
      - streamlit==1.31.1
      - tini==0.19.0
      - tip==3.0.3
      - torchvision==0.16.1
      - umap-learn==0.5.6
      - widgetsnbextension==4.0.13
      - pymongo==4.6.2
      - ruff==0.3.0
      - psycopg2==2.9.9
      - psycopg2-binary==2.9.9
      - sqlalchemy==2.0.28
      - zict==3.0.0
