apiVersion: v1
kind: Service
metadata:
  name: "operator"
  namespace: {{ .Values.operator.namespace }}
  labels:
    {{- include "minio-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4222
      name: https
  selector:
    operator: leader
    {{- include "minio-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: "sts"
  namespace: {{ .Values.operator.namespace }}
  labels:
    {{- include "minio-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 4223
      name: https
  selector:
    {{- include "minio-operator.selectorLabels" . | nindent 4 }}
