{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-operator
  namespace: {{ .Values.operator.namespace }}
  labels:
{{ include "minio-operator.labels" . | nindent 4 }}
{{- end }}