apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "jupyterhub.fullname" . }}-proxy-api
  labels:
    app.kubernetes.io/component: proxy
spec:
  selector:
    {{- include "jupyterhub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  {{- with .Values.serviceApi }}
  ports:
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
