apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "jupyterhub.fullname" . }}-proxy-public
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  selector:
    {{- include "jupyterhub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  {{- with .Values.servicePublic }}
  ports: {{ toYaml .ports | nindent 4 }}
  type: {{ .type }}
  {{- end }}
