apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.servicePublic.name }}
  labels:
    component: proxy
spec:
  selector:
    {{- include "jupyterhub.selectorLabels" . | nindent 4 }}
    component: proxy
  ports: {{ toYaml .Values.servicePublic.ports | nindent 4}}
  type: {{ .Values.servicePublic.type}}
