{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "jupyterhub.fullname" . }}-metrics
  labels:
    {{- include "jupyterhub.labels" . | nindent 4}}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: {{ .Values.metrics.port | default "8081" }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "jupyterhub.selectorLabels" . | nindent 4 }}
{{- end }}
