apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: nginx
  name: {{ include "nginx.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/nginx-default: "true"
        io.kompose.service: nginx
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: nginx
          image: "{{ .Values.image.registry}}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
          volumeMounts:
          - name: nginxconfig-mnt
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: nginx-claim
            mountPath: /usr/share/nginx/html
            readOnly: false
      volumes:
      - name: nginxconfig-mnt
        configMap:
          name: nginxconfig
      - name: nginx-claim
        persistentVolumeClaim:
          claimName: nginx-claim