apiVersion: v2
name: keycloak
version: 1.1
appVersion: 25.0.2
description: Open Source Identity and Access Management For Modern Applications and Services
keywords:
  - sso
  - idm
  - openid connect
  - saml
  - kerberos
  - ldap
home: https://www.keycloak.org/
icon: https://www.keycloak.org/resources/images/keycloak_icon_512px.svg
#dependencies:
#  - name: postgresql
#    version: 10.3.13
#    repository: file://./deps/postgresql
#    condition: postgresql.enabled
annotations:
  helm.sh/images: |
    - name: keycloak
      image: registry1.dso.mil/ironbank/opensource/keycloak/keycloak:25.0.5
#    - name: postgresl12
#      condition: postgresql.enabled
#      image: registry1.dso.mil/ironbank/opensource/postgres/postgresql12:12.15
