apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.name }}
type: Opaque
data:
  public.crt: |-
    {{ .Files.Get "tls.crt" | b64enc }}
  tls.crt: |-
    {{ .Files.Get "tls.crt" | b64enc }}
  tls.key: |-
    {{ .Files.Get "tls.key" | b64enc }}