apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: jupyterhub-startup-script
data:
  startup_script.bash: |-
    {{- .Files.Get "configs/startup_script.bash" | nindent 6 }}