apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: metaflow-datastore
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
  resources:
    requests:
      storage: {{ .Values.resources.storage }}



      