apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: metaflow-datastore
spec:
  accessModes:
    - ReadWriteMany
{{- if .Values.resources.useAzureFile }}
  storageClassName: azurefile-csi-singleuser
{{- end }}
{{- if .Values.resources.useAmazonFile}}
  storageClassName: efs-sc
{{- end }}  
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.resources.storage }}



      