apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: metaflow-datastore
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d220ea8b1d91428d::fsap-0e017c92ac3b7bfde
  resources:
    requests:
      storage: {{ .Values.resources.storage }}



      