{{ $secretName := ( include "get.tokenName" .) }}
{{- $secret := lookup "v1" "Secret" .Values.namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
{{- if $secret }}
  COOKIE_SECRET: {{ index $secret.data "COOKIE_SECRET" }}
  JUPYTERHUB_API_TOKEN: {{index $secret.data "JUPYTERHUB_API_TOKEN" }}
  JUPYTERHUB_CRYPT_KEY: {{index $secret.data "JUPYTERHUB_CRYPT_KEY" }}
  KEYCLOAK_JUPYTERHUB_CLIENT_SECRET: {{index $secret.data "KEYCLOAK_JUPYTERHUB_CLIENT_SECRET" }}
{{- else -}}
{{- $COOKIE_SECRET := ( randAlphaNum 64) }}
  COOKIE_SECRET: {{ $COOKIE_SECRET | b64enc }}
  JUPYTERHUB_API_TOKEN: {{ ( randAlphaNum 64 | b64enc)  }}
  JUPYTERHUB_CRYPT_KEY: {{ (include "jupyterhub.randHex" 64 | b64enc) }}
  KEYCLOAK_JUPYTERHUB_CLIENT_SECRET: {{ $COOKIE_SECRET | b64enc }}
{{- end }}
