apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: proxy-api
  labels:
    component: proxy
spec:
  selector:
    component: proxy
  ports:
    - protocol: TCP
      port: {{ .Values.serviceApi.port }}
      targetPort: {{.Values.serviceApi.targetPort}}


