{{- if .Values.gitSync.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: opal-sync-pvc
spec:
  accessModes:
    - ReadWriteMany
{{- if .Values.resources.useAzureFile }}
  storageClassName: azurefile-csi
{{- end }}
  resources:
    requests:
      storage: {{ .Values.resources.gitStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: weave-sync-pvc
spec:
  accessModes:
    - ReadWriteMany
{{- if .Values.resources.useAzureFile }}
  storageClassName: azurefile-csi
{{- end }}
  resources:
    requests:
      storage: {{ .Values.resources.gitStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: ddapi-sync-pvc
spec:
  accessModes:
    - ReadWriteMany
{{- if .Values.resources.useAzureFile }}
  storageClassName: azurefile-csi
{{- end }}
  resources:
    requests:
      storage: {{ .Values.resources.gitStorage }}
{{- end }}
