apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: opal-sync-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      {{- if .Values.gitSync.enabled }}
      storage: {{ .Values.resources.git-storage }}
      {{- else }}
      storage: 4Mi
      {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: weave-sync-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      {{- if .Values.gitSync.enabled }}
      storage: {{ .Values.resources.git-storage }}
      {{- else }}
      storage: 4Mi
      {{- end }}
