{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "jupyterhub.ingress.fullname" .}}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  rules:
  {{- with .Values.ingress.rules }}
    - host: {{ tpl .host $ | default (include "ingresses.jhub" $) | quote }}
      http: 
        paths: 
        {{- range .http.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "jupyterhub.proxy-public.fullname" $ }}
                port: 
                  name: http
        {{- end }}
  {{- end }}
{{- end }}
