apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: jupyterhub-toplevel-condarc
data:
  .condarc: |
    anaconda_upload: false
    channels:
      - nodefaults
    channel_priority: strict
    ssl_verify: false
