apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: metaflow-datastore
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  storageClass: azurefile-csi
  resources:
    requests:
      storage: 256Gi
