apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: metaflow-datastore
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.resources.useAzureFile }}
  storageClassName: azurefile-csi
  {{- end }}
  {{- if .Values.resources.useAmazonFile }}
  storageClassName: efs-csi
  volumeMode: Filesystem
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.resources.storage }}
