{{- if not .Values.tokenenv.existingSecret }}
---
# jupyterhub-specific secrets
{{ $secretName := ( include "get.tokenName" .) }}
{{- $secret := lookup "v1" "Secret" .Values.namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- if $secret }}
  COOKIE_SECRET: {{ index $secret.data "COOKIE_SECRET" }}
  JUPYTERHUB_API_TOKEN: {{index $secret.data "JUPYTERHUB_API_TOKEN" }}
  JUPYTERHUB_CRYPT_KEY: {{index $secret.data "JUPYTERHUB_CRYPT_KEY" }}
{{- else -}}
{{- $COOKIE_SECRET := ( randAlphaNum 64) }}
  COOKIE_SECRET: {{ $COOKIE_SECRET | b64enc }}
  JUPYTERHUB_API_TOKEN: {{ ( randAlphaNum 64 | b64enc)  }}
  JUPYTERHUB_CRYPT_KEY: {{ (include "jupyterhub.randHex" 64 | b64enc) }}
{{- end }}
---
{{- if not .Values.oauth.existingSecret }}
# client secret for oauth provider
{{ $secretName := ( include "get.oauthName" .) }}
{{- $secret := lookup "v1" "Secret" .Values.namespace $secretName }}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- if .Values.secrets.oauth.clientSecret }}
  KEYCLOAK_JUPYTERHUB_CLIENT_SECRET: {{ .Values.secrets.oauth.clientSecret }}
{{- else -}}
{{- $OAUTH_SECRET := ( randAlphaNum 64) }}
  KEYCLOAK_JUPYTERHUB_CLIENT_SECRET: {{ $OAUTH_SECRET | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end}}