{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "jupyterhub.hub-serviceaccount.fullname" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: jupyter
{{ end }}
