{{- if .Values.resources.useAmazonFile}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0d220ea8b1d91428d
  directoryPerms: "755"
  gidRangeStart: "100" # optional
  gidRangeEnd: "2000" # optional
  # basePath: "/dynamic_provisioning" # optional
  # subPathPattern: "${.PVC.namespace}/${.PVC.name}" # optional
  # ensureUniqueDirectory: "true" # optional
  # reuseAccessPoint: "false" # optional
{{- end }}