# Optionally override the fully qualified name
fullnameOverride: ""

# Optionally override the name
nameOverride: ""

# Namespace to install nginx
namespace: "opal"

name: nginx

baseDns: "10.96.30.9.nip.io"

image:
  registry: registry1.dso.mil
  repository: ironbank/opensource/nginx/nginx
  tag: 1.25.3
  pullPolicy: IfNotPresent

condaChannelImage:
  registry: registry1.dso.mil
  repository: ironbank/opensource/metrostar/pytorch
  tag: cuda_v3
  pullPolicy: IfNotPresent
  
imagePullSecrets: 
  name: regcred

ingress:
  enabled: false
  className: ""
  annotations: 
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  rules:
    host: "nginx-k8.{{ .Values.baseDns }}"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx
              port:
                number: 80
  tls: []

resources:
  storage: 3Gi
