name: nginx

namespace: opal

baseDns: "10.96.30.9.nip.io"

image:
  registry: registry1.dso.mil
  repository: ironbank/opensource/nginx/nginx
  tag: 1.25.3
  pullPolicy: IfNotPresent
  
imagePullSecrets: 
  name: regcred

ingress:
  enabled: true
  className: ""
  annotations: 
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  rules:
    host: "nginx-k8.{{ .Values.baseDns }}"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: proxy-public
              port:
                number: 8080
  tls: []