# leave these empty to disable them in the rendered app yamls
argoProject: &argoProj ""
appPrefix: &appPrefix ""

namespaces:
  - &minioNS minio-prod
  - &opalNS opal-prod

# an unfortunate requirement of project-scoping the app-of-apps
appNamespace: *opalNS

imagePullSecrets:
  name: regcred
  namespaces:
    - *opalNS
    - *minioNS

useAzureFile: &useAzure false
useAmazonFile: &useAmazon true

gitSyncSecret:
  namespace: *opalNS
  secretName: &gitSyncSecret "git-creds"

tls:
  name: tls-certs
  namespaces:
    - *minioNS
    - *opalNS

oauth:
  name: opal-oauth-common
  namespaces:
    - *opalNS
    - *minioNS

valuesFile: test-values.yaml

source: &appSource
  url: "https://github.com/309thEDDGE/opal-helm.git"
  targetRevision: "OPAL-1241-full-k8s-onprod"

# Most of this is just propagating settings from above, but change as needed for your use case
appValues:
  namespaces:
    - *opalNS
    - *minioNS
  argoProject: *argoProj
  appPrefix: *appPrefix
  source: *appSource
  mongodb:
    enabled: true
    appValues:
      namespaceOverride: *opalNS
      namespace: *opalNS
      auth:
        enabled: true
        rootUser: rootuser
        rootPassword: ""
        usernames: []
        passwords: []
        databases: []
      replicaCount: 2
  keycloak:
    namespace: *opalNS
    enabled: true
    # bootstrapper admin credentials. User should be disabled after post-install setup
    appValues:
      namespace: *opalNS
      secrets:
        env:
          stringData:
            KEYCLOAK_ADMIN: "admin"
            KEYCLOAK_ADMIN_PASSWORD: ""
            JAVA_OPTS_APPEND: -Djgroups.dns.query=""
    postgres:
      namespace: *opalNS
  traefik:
    enabled: true
    appValues:
      namespace: *opalNS
      service:
        annotations:
          # Uncomment for use in AWS
          service.beta.kubernetes.io/aws-load-balancer-type: "external"
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
          service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-014ea3b6f578bf649
          service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
          service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-09c8b32b3905fc6a8
          # uncomment for use in Azure
          # service.beta.kubernetes.io/azure-load-balancer-resource-group: opal-eval_group
          # service.beta.kubernetes.io/azure-pip-name: opal-PIP
          # service.beta.kubernetes.io/azure-dns-label-name: opal-eval
        externalIPs: 
        - 52.222.114.186
      ingress:
        enabled: false
  minioOperator:
    enabled: true
    appValues:
      operator:
        namespace: *opalNS
        tenantNamespace: *minioNS
  minioInstance:
    enabled: true
    creds:
      namespace: *minioNS
    secrets:
      accessKey: opal-administrator
    appValues:
      tenant:
        namespace: *minioNS
      oauth:
        existingSecret: "minio-creds-secret"
  nginx:
    enabled: true
    appValues:
      namespace: *opalNS
    restart: always
  jupyterhub:
    enabled: true
    appValues:
      namespace: *opalNS
      resources:
        useAzureFile: *useAzure
        useAmazonFile: *useAmazon
      gitSync:
        enabled: true
        username: ""
        gitSecret:
          secretName: *gitSyncSecret
        image:
          repository: registry.k8s.io/git-sync/git-sync
          tag: v4.0.0
  daskGateway:
    enabled: true
    appValues:
      namespace: *opalNS
