argoProject: default

namespaces:
  - &minioNS minio-tenant
  - &opalNS opal

imagePullSecrets:
  name: regcred
  namespaces:
    - *opalNS
    - *minioNS

tls:
  name: tls-certs
  namespaces:
    - *minioNS
    - *opalNS

oauth:
  name: opal-oauth-common
  namespaces:
    - *opalNS
    - *minioNS

valuesFile: test-values.yaml

token:
  name: &token-env "token-env"
  namespaces:
    - *opalNS

minio:
  name: &minio-creds "minio-creds-secret"
  accesskey: &minio-accesskey opal-administrator

keycloakenv:
  name: &keycloak-env "opal-setup-keycloak-env"
  namespaces:
    - *opalNS
    - *minioNS

postgresql:
  name: &keycloak-postgres "opal-setup-keycloak-postgres"
  namespaces:
    - *opalNS
    - *minioNS

mongodb:
  name: &mongo-secret "opal-setup-mongodb"
  namespaces:
    - *opalNS


source: &appSource
  url: "https://github.com/309thEDDGE/opal-helm.git"
  targetRevision: "OPAL-1175-argocd-secrets-sync"

appValues:
  source: *appSource
  mongodb:
    enabled: true
    appValues:
      auth:
        existingSecret: *mongo-secret
  keycloak:
    enabled: true
    # bootstrapper admin credentials. Should be deleted after post-install setup
    appValues:
      secrets:
        env:
          existingSecret: *keycloak-env
          annotations: {}
          stringData:
            KEYCLOAK_ADMIN: "admin"
            KEYCLOAK_ADMIN_PASSWORD: "password"
            JAVA_OPTS_APPEND: -Djgroups.dns.query=opal-setup-keycloak-headless
        oauth:
          existingSecret: &oauthSecret "opal-oauth-common"
    postgresql:
      existingSecret: *keycloak-postgres
  traefik:
    enabled: true
  minioOperator:
    enabled: true
  minioInstance:
    enabled: true
    namespace: *minioNS
    appValues:
      creds:
        existingSecret: *minio-creds
        accessKey: *minio-accesskey
  jupyterhub:
    enabled: true
    appValues:
      secrets:
        tokenenv:
          existingSecret: *token-env
        oauth:
          existingSecret: *oauthSecret