# leave these empty to disable them in the rendered app yamls
argoProject: &argoProj ""
appPrefix: &appPrefix ""

namespaces:
  - &minioNS minio-tenant
  - &opalNS opal

# an unfortunate requirement of project-scoping the app-of-apps
appNamespace: *opalNS

imagePullSecrets:
  name: regcred
  namespaces:
    - *opalNS
    - *minioNS

useAzureFile: &useAzure false

gitSyncSecret:
  namespace: *opalNS
  secretName: &gitSyncSecret "git-creds"

tls:
  name: tls-certs
  namespaces:
    - *minioNS
    - *opalNS

oauth:
  name: opal-oauth-common
  namespaces:
    - *opalNS
    - *minioNS

valuesFile: test-values.yaml

source: &appSource
  url: "https://github.com/309thEDDGE/opal-helm.git"
  targetRevision: "opal-1253-reintegrate-app-prefixes"

# Most of this is just propagating settings from above, but change as needed for your use case
appValues:
  namespaces:
    - *opalNS
    - *minioNS
  argoProject: *argoProj
  appPrefix: *appPrefix
  source: *appSource
  mongodb:
    enabled: true
    appValues:
      namespaceOverride: *opalNS
      namespace: *opalNS
  keycloak:
    namespace: *opalNS
    enabled: true
    # bootstrapper admin credentials. User should be disabled after post-install setup
    appValues:
      namespace: *opalNS
      secrets:
        env:
          stringData:
            KEYCLOAK_ADMIN: "admin"
            KEYCLOAK_ADMIN_PASSWORD: ""
            JAVA_OPTS_APPEND: -Djgroups.dns.query=""
    postgres:
      namespace: *opalNS
  traefik:
    enabled: true
    appValues:
      namespace: *opalNS
  minioOperator:
    enabled: true
    appValues:
      operator:
        namespace: *opalNS
        tenantNamespace: *minioNS
  minioInstance:
    enabled: true
    creds:
      namespace: *minioNS
    secrets:
      accessKey: opal-administrator
    appValues:
      tenant:
        namespace: *minioNS
      oauth:
        existingSecret: "minio-creds-secret"
  nginx:
    enabled: true
    appValues:
      namespace: *opalNS
    restart: always
  jupyterhub:
    enabled: true
    appValues:
      namespace: *opalNS
      resources:
        useAzureFile: *useAzure
      gitSync:
        enabled: true
        username: ""
        gitSecret:
          secretName: *gitSyncSecret
  daskGateway:
    enabled: true
    appValues:
      namespace: *opalNS
