argoProject: default

namespaces:
  - &minioNS minio-tenant
  - &opalNS opal

imagePullSecrets:
  name: regcred
  namespaces:
    - *opalNS
    - *minioNS

gitSyncSecret:
  namespace: *opalNS
  secretName: &gitSyncSecret "git-creds"

tls:
  name: tls-certs
  namespaces:
    - *minioNS
    - *opalNS

oauth:
  name: &oauthSecret opal-oauth-common
  namespaces:
    - *opalNS
    - *minioNS

valuesFile: test-values.yaml

token:
  name: &token-env "token-env"
  namespaces:
    - *opalNS

minio:
  name: &minio-creds "minio-creds-secret"
  accesskey: &minio-accesskey opal-administrator
  namespaces:
    - *minioNS

keycloakenv:
  name: &keycloak-env "opal-setup-keycloak-env"
  namespaces:
    - *opalNS
    - *minioNS

postgresql:
  name: &keycloak-postgres "opal-setup-keycloak-postgres"
  namespaces:
    - *opalNS
    - *minioNS

mongodb:
  name: &mongo-secret "opal-setup-mongodb"
  architecture: &mongodb-architecture standalone
  namespaces:
    - *opalNS

source: &appSource
  url: "https://github.com/309thEDDGE/opal-helm.git"
  targetRevision: "main"

appValues:
  source: *appSource
  mongodb:
    enabled: true
    appValues:
      architecture: *mongodb-architecture
      auth:
        existingSecret: *mongo-secret
        enabled: true
        rootUser: rootuser
        rootPassword: ""
        usernames: []
        passwords: []
        databases: []
      replicaCount: 2
  keycloak:
    enabled: true
    # bootstrapper admin credentials. Should be deleted after post-install setup
    appValues:
      secrets:
        env:
          existingSecret: *keycloak-env
          annotations: {}
          stringData:
            KEYCLOAK_ADMIN: "admin"
            KEYCLOAK_ADMIN_PASSWORD: ""
            JAVA_OPTS_APPEND: -Djgroups.dns.query=opal-setup-keycloak-headless
        oauth:
          existingSecret: *oauthSecret
    postgresql:
      existingSecret: *keycloak-postgres

  traefik:
    enabled: true
  minioOperator:
    enabled: true
  minioInstance:
    enabled: true
    namespace: *minioNS
    appValues:
      creds:
        existingSecret: *minio-creds
        accessKey: *minio-accesskey   
        
  jupyterhub:
    enabled: true
    appValues:
      namespace: *opalNS
      secrets:
        tokenenv:
          existingSecret: *token-env
        oauth:
          existingSecret: *oauthSecret
      instance:
        namespace: *minioNS
      gitSync:
        enabled: true
        username: ""
        gitSecret:
          secretName: *gitSyncSecret
        image:
          repository: registry.k8s.io/git-sync/git-sync
          tag: v4.0.0
