argoProject: &argoProj default
appPrefix: &appPrefix default

namespaces:
  - &minioNS minio-tenant
  - &opalNS opal

imagePullSecrets:
  name: regcred
  namespaces:
    - *opalNS
    - *minioNS

tls:
  name: tls-certs
  namespaces:
    - *minioNS
    - *opalNS

oauth:
  name: opal-oauth-common

valuesFile: test-values.yaml

source: &appSource
  url: "https://github.com/309thEDDGE/opal-helm.git"
  targetRevision: "main"

appValues:
  namespaces:
    - *opalNS
    - *minioNS
  argoProject: *argoProj
  appPrefix: *appPrefix
  source: *appSource
  mongodb:
    enabled: true
    appValues:
      namespace: *opalNS
      global:
        namespaceOverride: *opalNS
  keycloak:
    enabled: true
    # bootstrapper admin credentials. Should be deleted after post-install setup
    appValues:
      namespace: *opalNS
      secrets:
        env:
          annotations: {}
          stringData:
            KEYCLOAK_ADMIN: "admin"
            KEYCLOAK_ADMIN_PASSWORD: ""
            JAVA_OPTS_APPEND: -Djgroups.dns.query=opal-setup-keycloak-headless
  traefik:
    enabled: true
    appValues:
      namespace: *opalNS
  minioOperator:
    enabled: true
    appValues:
      operator:
        namespace: *opalNS
        tenantNamespace: *minioNS
  minioInstance:
    enabled: true
    creds:
      namespace: *minioNS
    secrets:
      accessKey: opal-administrator
    appValues:
      tenant:
        namespace: *minioNS
      oauth:
        existingSecret: minio-creds-secret
  jupyterhub:
    enabled: true
    appValues:
      namespace: *opalNS
    postgres:
      namespace: *opalNS