argoProject: default

namespaces:
  - &minioNS minio-tenant
  - &opalNS opal

imagePullSecrets:
  name: regcred

tls:
  name: tls-certs
  namespaces:
    - *minioNS
    - *opalNS

oauth:
  name: opal-oauth-common

valuesFile: test-values.yaml

source: &appSource
  url: "https://github.com/309thEDDGE/opal-helm.git"
  targetRevision: "argo-architecture"

appValues:
  source: *appSource
  mongodb:
    enabled: true
  keycloak:
    enabled: true
  traefik:
    enabled: true
  minio-operator:
    enabled: false
  minio-instance:
    enabled: false
  jupyterhub:
    enabled: false
