apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{include "jupyterhub.fullname" . }}-hub
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: jupyter
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: http
      name: hub
  selector:
    {{- include "jupyterhub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: jupyter
