{{- $values := .Values }}
{{- $files := .Files }}
{{- $release:= .Release }}

{{- range .Values.imagePullSecrets.namespaces }}
---
# Generates regcred for the opal and minio namespaces
apiVersion: v1
kind: Secret
metadata:
  name: {{ $values.imagePullSecrets.name }}
  namespace: {{ . }}
  annotations:
    argocd.argoproj.io/hook: Skip
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $files.Get "dockerconfig.json" | b64enc }}
  {{- end }}
