{{- $values := .Values }}
{{- $files := .Files }}
{{- $release:= .Release }}

---
{{- $secretName := "{{ $release.Name }}-keycloak-env" }}
{{- $secret := lookup "v1" "Secret" .Values.appValues.keycloak.namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $release.Name }}-keycloak-env
  namespace: {{ .Values.appValues.keycloak.namespace }}
  {{- with $values.appValues.keycloak.appValues.secrets.env.annotations }}
  annotations:
  {{- range $key, $value := . }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
type: {{ default "Opaque" $values.appValues.keycloak.appValues.secrets.type }}
{{- with $values.appValues.keycloak.appValues.secrets.env.stringData }}
stringData:
  {{- range $key, $value := . }}
    {{- if eq $key "KEYCLOAK_ADMIN_PASSWORD"}}
      {{- if $secret }}
  KEYCLOAK_ADMIN_PASSWORD: {{ index $secret.data "KEYCLOAK_ADMIN_PASSWORD" | b64dec }}
      {{- else }}
    {{- printf "%s: %s" $key (( randAlphaNum 16 ) | quote) | nindent 2 }}
      {{- end }}
    {{- else if eq $key "JAVA_OPTS_APPEND"}}
  JAVA_OPTS_APPEND: -Djgroups.dns.query={{ $release.Name }}-keycloak-headless
    {{- else }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 2 }}
    {{- end }}
  {{- end }}
{{- end }}
