apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-copy-conda-channel
data:
  copy-conda-channel.sh: |-
{{- .Files.Get "config/copy_conda_channel.sh" | nindent 6 }}
