apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-nginx
  labels:
    component: nginx
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    component: nginx
