  appValues:
    namespace: opal
    secrets:
      env:
        stringData:
          # both fields need to be filled in
          KEYCLOAK_ADMIN: ""
          KEYCLOAK_ADMIN_PASSWORD: ""
    ingress:
      enabled: true
      rules:
        host: ""
    postgresql:
      enabled: true
      nameOverride: keycloak-postgres
      namespace: opal
    keycloakSetup:
      existingSecret: opal-oauth-common
  source:
    url: ""
    targetRevision: ""
    path: ""
