{{- $values := .Values }}
{{- $files := .Files }}

{{- range .Values.tls.namespaces }}
---
# Generates the tls certs for opal and minio-tenant
apiVersion: v1
kind: Secret
metadata:
  name: {{ $values.tls.name }}
  namespace: {{ . }}
type: Opaque
data:
  public.crt: |-
    {{ $files.Get "tls.crt" | b64enc }}
  tls.crt: |-
    {{ $files.Get "tls.crt" | b64enc }}
  tls.key: |-
    {{ $files.Get "tls.key" | b64enc }}
  {{- end }}
