{{- if .Values.keycloakSetup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-setup
  namespace: {{ .Values.namespace }}
data:
  keycloak-setup.sh: |-
    {{- .Files.Get "keycloak-setup.sh" | nindent 6 -}}
{{- end }}
