{{- if .Values.startupScripts }}
{{- $highAvailability := gt (int .Values.replicas) 1 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-startup
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.startupScripts }}
  {{ $key }}: |
    {{- tpl $value $ | nindent 4 }}
  {{- end }}
{{- end -}}
