{{- $secrets := .Values.secrets.env }}
---
{{- if not .Values.keycloakSetup.existingSecret}}
# client secret for oauth provider
{{- $secretName := ( include "get.oauthName" .) }}
{{- $secret := lookup "v1" "Secret" .Values.namespace $secretName }}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- if .Values.keycloakSetup.clientSecret }}
  KEYCLOAK_JUPYTERHUB_CLIENT_SECRET: {{ .Values.keycloakSetup.clientSecret }}
  {{- else }}
  {{- $OAUTH_SECRET := ( randAlphaNum 64) }}
  KEYCLOAK_JUPYTERHUB_CLIENT_SECRET: {{ $OAUTH_SECRET | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
