{{- $values := . }}
{{- range $key, $serviceMonitor := dict "metrics" .Values.serviceMonitor "extra" .Values.extraServiceMonitor }}
{{- with $serviceMonitor }}
{{- if .enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "keycloak.fullname" $ }}-{{ $key }}
  namespace: {{ .namespace }}
  {{- with .annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
  {{- include "keycloak.labels" $ | nindent 4 }}
  {{- range $key, $value := .labels }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
  {{- end }}
spec:
  {{- with .namespaceSelector }}
  namespaceSelector:
  {{- tpl . $ | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: metrics
  endpoints:
    - port: {{ .port }}
      path: {{ .path }}
      interval: {{ .interval }}
      scrapeTimeout: {{ .scrapeTimeout }}
      {{- if .scheme }}
      scheme: {{ .scheme }}
      {{- end }}
      {{- if .tlsConfig }}
      tlsConfig:
        {{- toYaml .tlsConfig | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
