---
# Source: minio-instance/templates/tenant-configuration.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio123"
data:
  ## Access Key for MinIO Tenant
  accesskey: bWluaW8=
  ## Secret Key for MinIO Tenant
  secretkey: bWluaW8xMjM=
---
# Source: minio-instance/templates/tenant.yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: release-name-minio-instance
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
  
spec:
  image: registry1.dso.mil/ironbank/opensource/minio/minio:RELEASE.2023-06-19T19-52-50Z
  imagePullPolicy: IfNotPresent
  imagePullSecret:
    name: private-registry
  ## Secret with credentials to be used by MinIO Tenant.:
  configuration:
    name: minio-creds-secret
  pools:
    - servers: 4
      name: 
      volumesPerServer: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: 
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 1000m
          memory: 2Gi
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      containerSecurityContext:
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
  mountPath: /home/minio
  subPath: /data
  requestAutoCert: false
  features:
    bucketDNS: false
  podManagementPolicy: Parallel
  prometheusOperator: false
  logging:
    anonymous: true
    json: true
    quiet: true
