{{- if .Values.useAzureFile }}
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-singleuser
mountOptions:
- dir_mode=0755
- file_mode=0600
- uid=1000
- gid=100
- mfsymlinks
- actimeo=30
- nosharesock
parameters:
  skuName: Standard_LRS
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
{{- end }}
