{{- $values := .Values }}
{{- $files := .Files }}

# Generates git creds for jhub
apiVersion: v1
kind: Secret
metadata:
  name: {{ $values.gitSyncSecret.secretName }}
  namespace: {{ $values.gitSyncSecret.namespace }}
  annotations:
    argocd.argoproj.io/hook: Skip
type: Opaque
data:
  token: {{ $files.Get "git-creds" | b64enc }}