{{- $values := .Values }}
{{- $files := .Files }}

{{- range .Values.tls.namespaces }}
{{ $secret := (lookup "v1" "Secret" . $values.tls.name )}}
  {{ if not $secret }}
# Generates the tls certs for opal and minio-tenant
apiVersion: v1
kind: Secret
metadata:
  name: {{ $values.tls.name }}
  namespace: {{ . }}
  annotations:
    argocd.argoproj.io/hook: Skip
type: Opaque
data:
  public.crt: |-
    {{ $files.Get "tls.crt" | b64enc }}
  tls.crt: |-
    {{ $files.Get "tls.crt" | b64enc }}
  tls.key: |-
    {{ $files.Get "tls.key" | b64enc }}
  {{- end }}
{{- end }}
---