{{- $values := .Values }}
{{- $files := .Files }}

{{- range .Values.imagePullSecrets.namespaces }}
---
# Generates the regcred for opal and minio-tenant
apiVersion: v1
kind: Secret
metadata:
  name: {{ $values.imagePullSecrets.name }}
  namespace: {{ . }}
  annotations:
    argocd.argoproj.io/hook: Skip
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $files.Get "dockerconfig.json" | b64enc }}
  {{- end }}
{{- range .Values.tls.namespaces }}
---
# Generates the tls certs for opal and minio-tenant
apiVersion: v1
kind: Secret
metadata:
  name: {{ $values.tls.name }}
  namespace: {{ . }}
  annotations:
    argocd.argoproj.io/hook: Skip
type: Opaque
data:
  public.crt: |-
    {{ $files.Get "tls.crt" | b64enc }}
  tls.crt: |-
    {{ $files.Get "tls.crt" | b64enc }}
  tls.key: |-
    {{ $files.Get "tls.key" | b64enc }}
  {{- end }}

{{- $OAUTH_SECRET := ( randAlphaNum 64) }}

{{- range .Values.namespaces }}
---
# Generates shared secrets
{{ $secretName := $values.oauth.name }}
#{{ $ns := . }}
{{- $secret := lookup "v1" "Secret" . $secretName }}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ . }}
  annotations:
    argocd.argoproj.io/hook: Skip
type: Opaque
data:
  KEYCLOAK_SECRET: {{ $OAUTH_SECRET | b64enc }}
  MINIO_IDENTITY_OPENID_CLIENT_SECRET: {{ $OAUTH_SECRET | b64enc }}
  KEYCLOAK_JUPYTERHUB_CLIENT_SECRET: {{ $OAUTH_SECRET | b64enc }}
{{- end }}
{{- end }}

---
{{- if dig "secrets" true (.Values | merge (dict)) }}
{{- $ROOT_PASSWORD := (randAlphaNum 16 | quote)}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minioInstance.appValues.oauth.existingSecret }}
  namespace: {{ .Values.minioInstance.creds.namespace }}
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER={{ .Values.secrets.accessKey | quote }}
    export MINIO_ROOT_PASSWORD={{$ROOT_PASSWORD}}
    export MINIO_IDENTITY_OPENID_CLIENT_SECRET: {{ $OAUTH_SECRET | b64enc }}

data:
  ## Access Key for MinIO Tenant
  accesskey: {{ dig "secrets" "accessKey" "" (.Values | merge (dict)) | b64enc }}
  ## Secret Key for MinIO Tenant
  secretkey: {{$ROOT_PASSWORD | b64enc }}
  {{- end }}
