{{- if .Values.rbac.enabled }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "traefik.fullname" . }}-role-binding
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "traefik.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "traefik.fullname" . }}-account
    namespace: {{ .Values.namespace }}
{{- end }}
