apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "traefik.fullname" . }}
  labels:
    app: {{ include "traefik.fullname" . }}
    {{- include "traefik.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ default 1 .Values.autoscaling.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "traefik.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "traefik.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "traefik.fullname" .}}-account
      containers:
        - name: {{ include "traefik.fullname" . }}
          image: registry1.dso.mil/ironbank/opensource/traefik/traefik:v2.9.1
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 8443
          volumeMounts:
            - name: traefik-cfg
              mountPath: /etc/traefik/traefik.toml
              subPath: file-from-cfgmap
            - name: traefik-cfg-dynamic
              mountPath: /etc/traefik/traefik_dynamic.yml
              subPath: file-from-cfgmap
            - name: traefik-certs-files
              mountPath: /etc/traefik/certs
      volumes:
        - name: traefik-certs-files
          secret:
            {{- if not .Values.tls.nameOverride }}
            secretName: {{ include "traefik.fullname" .}}-tls-certs
            {{- else }}
            secretName: {{ .Values.tls.nameOverride }}
            {{- end }}
        - name: traefik-cfg-dynamic
          configMap:
            name: {{ include "traefik.fullname" . }}-config-dynamic
        - name: traefik-cfg
          configMap:
            name: {{ include "traefik.fullname" . }}-config
