{{ if .Values.ingress.enabled }}
{{- $ingress := .Values.ingress -}}
{{- $values := . -}}
{{- $apiV1 := false -}}
{{- $apiVersion := "extensions/v1beta1" -}}
{{- if and (.Capabilities.APIVersions.Has "networking.k8s.io/v1") (semverCompare ">= v1.19.0-0" .Capabilities.KubeVersion.Version) -}}
  {{- $apiVersion = "networking.k8s.io/v1" -}}
  {{- $apiV1 = true -}}
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" -}}
  {{- $apiVersion = "networking.k8s.io/v1beta1" -}}
{{- else -}}
  {{- $apiVersion = "extensions/v1beta1" -}}
{{- end }}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ include "traefik.fullname" . }}
  namespace: {{ .Values.namespace }}
  {{- with $ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
spec:
  rules:
    {{- with $ingress.rules }}
    -
      {{- if .host }}
      host: {{ .host | default (include "domains.traefik" $values) }}
      {{- end }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if $apiV1 }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "traefik.fullname" $ }}-service
                port:
                  name: dashboard
            {{- else }}
            backend:
              serviceName: {{ include "traefik.fullname" $ }}-service
              servicePort: dashboard
            {{- end }}
          {{- end }}
    {{- end }}
{{ end }}
