apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ include "traefik.fullname" . }}-metrics
  annotations:
    {{- .Values.service.annotations | toYaml | nindent 4 }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.service.labels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  selector:
    app: {{ include "traefik.fullname" . }}
  ports:
    - protocol: TCP
      port: 8082
      name: metrics
      targetPort: metrics
