---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "traefik.fullname" .}}-config-dynamic
data:
  file-from-cfgmap: |
    tls:
      certificates:
        - certFile: "/etc/traefik/certs/tls.crt"
          keyFile: "/etc/traefik/certs/tls.key"
      stores:
        default:
          defaultCertificate:
            certFile:  "/etc/traefik/certs/tls.crt"
            keyFile: "/etc/traefik/certs/tls.key"
